services:
  v2fly426:
    container_name: v2fly426
    image: v2fly/v2fly-core:v4.26.0
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - ./timechee.crt:/etc/v2ray/timechee.crt
      - ./timechee.key:/etc/v2ray/timechee.key
    network_mode: host
    environment:
      - "TZ=Asia/Jakarta"
